# Generated by Django 4.2.1 on 2024-04-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_service_category'),
        ('UserApp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes')),
                ('coverletter', models.CharField(max_length=500)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.service')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.register')),
            ],
        ),
    ]
