# Generated by Django 4.2.1 on 2024-04-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_job_delete_category'),
        ('UserApp', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sid',
        ),
        migrations.AddField(
            model_name='booking',
            name='jid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.job'),
        ),
    ]
