# Generated by Django 4.2.1 on 2024-04-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_eregister_password'),
        ('UserApp', '0004_remove_booking_sid_booking_jid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes')),
                ('coverletter', models.CharField(max_length=500)),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.eregister')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.register')),
            ],
        ),
    ]
