# Generated by Django 4.2.1 on 2024-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_ebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebooking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
