# Generated by Django 4.2.1 on 2024-04-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_ebooking_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooking',
            name='jid',
        ),
        migrations.AddField(
            model_name='ebooking',
            name='job',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ebooking',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.register'),
        ),
    ]
