# Generated by Django 4.2.1 on 2024-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=100)),
                ('qual', models.CharField(max_length=100)),
                ('img', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
    ]
