# Generated by Django 4.2.1 on 2024-04-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eregister',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
