# Generated by Django 4.2.1 on 2024-04-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='null.jpg', upload_to='images')),
                ('vacancy', models.IntegerField()),
                ('skill', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=20)),
                ('exp', models.IntegerField()),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
