# Generated by Django 4.2.1 on 2024-04-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_booking_sid_booking_jid'),
        ('AdminApp', '0004_job_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
